services:
  - type: web
    name: pureorigins-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_SAMESITE
        value: none